### ISSUE TITLE
怎样可以验证这个问题？

### ISSUE THREAD

**Issue by ruijun** [cat9/ToastCompat#1]
@cat9  Hello， 怎样可以验证这个问题呢？

**Comment by cat9** [comment]
虽然这个问题在7.1.1的机型上出现的概率挺高，然而并没有很好的方法去重现这个问题。
在看了7.1.1的Toast实现源码，就可以做出一个简单的捕获错误hack了。
这里的ToastCompat是用在我们项目上，并且得到验证了的（就是没再收到该bug的上报了）。

**Comment by ruijun** [comment]
发现一个问题，使用ToastCompat跟原生的Toast显示样式不一致，不知道是什么原因导致的

**Comment by cat9** [comment]
一般app都会自定义显示的View样式。
如果样式有差异的话，问题就在这里：[相关代码](https://github.com/cat9/ToastCompat/blob/4ba08b88e398d87c005262408c1d16d100e3b1e8/app/src/main/java/com/miku/toast/ToastCompat.java#L44)
这里由于不能直接引用到原生系统的资源（com.android.internal.R.layout.transient_notification），所以用了另外一个资源获取方式。
不过我看了各个版本的sdk源码，引用的都是transient_notification这个资源，和ToastCompat里面引用的是一致的。问题应该是你那个手机rom有改动，并没引用transient_notification这个资源。
所以如果你想保持一致的体验的话，最好自定义一个View，并使用它。

**Comment by ruijun** [comment]
我修改了makeText代码，使用Resources.getSystem()，样式还是跟原生的不一致。看来只能自己定义一个view了。
```java
public static Toast makeText(Context context, CharSequence text, int duration) {
        ToastCompat result = new ToastCompat(context);

        LayoutInflater inflate = (LayoutInflater)
                context.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        Resources resources = Resources.getSystem();
        View v = inflate.inflate(resources.getIdentifier("transient_notification", "layout", "android"), null);
        TextView tv = (TextView) v.findViewById(resources.getIdentifier("message", "id", "android"));
        tv.setText(text);
        result.setView(v);
        result.setDuration(duration);
        return result;
    }
```
